sudo: false
language: scala

scala:
  - 2.11.12
  - 2.12.7
jdk:
  - oraclejdk8
env:
  # marker environment variable to make the build matrix more readable in the UI
  - JOB=test

script:
  - sbt coverage "++$TRAVIS_SCALA_VERSION test" "++$TRAVIS_SCALA_VERSION tut" "++$TRAVIS_SCALA_VERSION doc"
  - (cd example ; sbt ++$TRAVIS_SCALA_VERSION test)

  # check if there are no changes after `tut` runs
  - if [[ $TRAVIS_SCALA_VERSION =~ ^2\.12.* ]]; then
      git diff --exit-code;
      fi

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "++$TRAVIS_SCALA_VERSION coverageReport" coverageAggregate coveralls

jobs:
  include:
    - env: JOB=microsite
      scala: 2.12.7
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev # required to avoid SSL errors
      before_install:
        - export PATH=${PATH}:./vendor/bundle
        - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      install:
        - rvm use 2.4 --install --fuzzy
        - gem update --system
        - gem install sass jekyll:3.2.1 html-proofer:3.9.3
      script:
        - sbt makeMicrosite
        - htmlproofer
            --allow-hash-href
            --url-swap "https\://github\.com/pureconfig/pureconfig/tree/master:file\://$(pwd)"
            --url-ignore "search.maven.org/artifact/com.github.pureconfig/pureconfig_2.12$"
            docs/target/site
      after_success: ignore

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
