language: scala
scala:
    - 2.10.6
    - 2.11.11
    - 2.12.4
jdk:
    - oraclejdk8
script:
  - sbt coverage "+++$TRAVIS_SCALA_VERSION test" "+++$TRAVIS_SCALA_VERSION tut" "+++$TRAVIS_SCALA_VERSION doc"
  - (cd example ; sbt ++$TRAVIS_SCALA_VERSION test)

  # check if there are no changes after `tut` runs
  - if [[ $TRAVIS_SCALA_VERSION =~ ^2\.12.* ]]; then
      git diff --exit-code;
      fi
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "+++$TRAVIS_SCALA_VERSION coverageReport" coverageAggregate coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
