name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [openjdk@1.8]
        scala: [2.11.12, 2.12.12, 2.13.3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.jdk }}

      - name: Check formatting
        run: sbt "++${{ matrix.scala }} scalafmtCheckAll; scalafmtSbtCheck"

      - name: Compile
        run: sbt coverage "++${{ matrix.scala }} compile"

      - name: Run tests
        run: sbt coverage "++${{ matrix.scala }} test"

      - name: Upload coverage data to Coveralls
        run: sbt ++${{ matrix.scala }} coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}

      - name: Build Scaladoc
        run: sbt "++${{ matrix.scala }} doc"

      - name: Publish artifact locally
        run: sbt "++${{ matrix.scala }} publishLocal"

      - name: Compile example project
        run: cd example && sbt "++${{ matrix.scala }} test"

      - name: Check tut and mdoc output
        if: startsWith(matrix.scala, '2.12')
        run: >
           sbt "++${{ matrix.scala }} tut" "++${{ matrix.scala }} mdoc" &&
           git diff --exit-code

  build_website:
    name: Build Website
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.8

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: >
          sudo apt install libxslt-dev &&
          gem install sass jekyll:4.0.0 html-proofer:3.9.3

      - name: Build website
        run: sbt makeMicrosite

      - name: Verify website
        run: >
          htmlproofer
          --allow-hash-href
          --url-swap "https\://github\.com/pureconfig/pureconfig/tree/master:file\://$(pwd)"
          --url-ignore "/search.maven.org/"
          docs/target/site

  diff_website:
    name: Diff Website
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.8

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: gem install sass jekyll:4.0.0

      - name: Build and compare website
        id: diff_website
        run: ./scripts/diff_website.sh
        continue-on-error: true

      - name: Comment on pull request
        if: steps.diff_website.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: >
            Warning: the content of the PureConfig website changed with this pull request. This may
            be intentional (as is the case when sbt-microsites is updated or some breaking change
            occurs) or may be an unexpected change in the library's behavior. Please check the logs
            of the [Diff Website job](https://github.com/pureconfig/pureconfig/actions/runs/${{ github.run_id }})
            ("Build and compare website" step) in GitHub Actions to see the differences.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
